// ============================================================
// Zany'sCollection — Shared Product Catalog
// This is the SINGLE SOURCE OF TRUTH for product data.
// index.html, shop.html, and product.html all read from here.
// To add/edit a product, change it ONLY in this file.
// ============================================================

const catLabels = { jewelry:'Jewelry', suits:'Pakistani Suits', bags:'Handbags' };

const catalog = [
  { id:1, cat:'jewelry', name:'Meherun Gold Choker', price:152, was:186, rating:4.9, reviews:112, badge:'Best Seller', stock:true, added:1,
    desc:'A statement gold choker hand-finished by our goldsmith partners in Lahore. Layered detailing catches light from every angle — built for wedding season, comfortable enough for a full evening.' },
  { id:2, cat:'suits', name:'Zoya Embroidered Lawn 3PC', price:35, was:null, rating:4.7, reviews:64, badge:'New', stock:true, added:4,
    desc:'Hand-embroidered lawn three-piece with a matching dupatta. Breathable fabric cut for warm-weather wear, with embroidery detailing along the neckline and hem.', sizes:['S','M','L','XL'] },
  { id:3, cat:'bags', name:'Ambar Structured Tote', price:51, was:63, rating:4.6, reviews:81, badge:'Sale', stock:true, added:2,
    desc:'A structured everyday tote in vegan leather, sized to fit a laptop or A4 folder. Reinforced base keeps its shape even when only half full.' },
  { id:4, cat:'jewelry', name:'Naaz Kundan Earrings', price:68, was:null, rating:4.8, reviews:47, badge:null, stock:true, added:2,
    desc:'Traditional kundan-set earrings with a secure screw-back fitting. Lightweight enough for all-day wear despite the statement size.' },
  { id:5, cat:'suits', name:'Rania Chiffon Formal 3PC', price:55, was:null, rating:4.5, reviews:33, badge:'New', stock:false, added:5,
    desc:'Formal chiffon three-piece with delicate thread work, designed for evening events. Fully lined for opacity and comfort.', sizes:['XS','S','M','L','XL'] },
  { id:6, cat:'bags', name:'Sana Quilted Sling', price:31, was:39, rating:4.4, reviews:58, badge:'Sale', stock:true, added:3,
    desc:'A quilted sling bag with an adjustable gold-tone chain strap. Compact enough for evenings, roomy enough for the essentials.' },
  { id:7, cat:'jewelry', name:'Layla Pearl Drop Set', price:80, was:null, rating:4.9, reviews:97, badge:null, stock:true, added:1,
    desc:'A necklace-and-earring set featuring freshwater pearl drops on a fine gold-plated chain. Understated enough for daily wear.' },
  { id:8, cat:'suits', name:'Amal Organza Bridal 3PC', price:121, was:null, rating:5.0, reviews:22, badge:'Best Seller', stock:true, added:3,
    desc:'Our most-requested bridal piece — hand-finished organza with dense embroidery across the bodice and hem. Made to order with a 2-week lead time.', sizes:['S','M','L','XL'] },
  { id:9, cat:'bags', name:'Farah Woven Clutch', price:22, was:null, rating:4.3, reviews:19, badge:null, stock:true, added:4,
    desc:'A hand-woven evening clutch with a magnetic clasp closure. Comes with a detachable wrist strap.' },
  { id:10, cat:'jewelry', name:'Deeba Rose Gold Bangles', price:99, was:111, rating:4.7, reviews:71, badge:'Sale', stock:true, added:2,
    desc:'A set of three rose-gold plated bangles with a matte-and-polish contrast finish. Sold as a set of three.' },
  { id:11, cat:'suits', name:'Nimra Cotton Casual 2PC', price:19, was:null, rating:4.2, reviews:40, badge:null, stock:true, added:5,
    desc:'An everyday cotton two-piece, pre-washed and pre-shrunk. Our most breathable fabric — built for daily wear, not just occasions.', sizes:['S','M','L','XL','XXL'] },
  { id:12, cat:'bags', name:'Iman Leather Crossbody', price:46, was:null, rating:4.6, reviews:36, badge:null, stock:false, added:1,
    desc:'A compact genuine-leather crossbody with an adjustable strap and interior card slots.' },
  { id:13, cat:'bags', name:'Jasmine Rose Pearl Clutch', price:35, was:null, rating:5.0, reviews:2, badge:'New', stock:true, added:6,
    img:'images/jasmine-rose-pearl-clutch.jpg',
    desc:'A hand-assembled rose-appliqué clutch with a pearl-beaded top handle. Each fabric rose is individually stitched — no two bags are perfectly identical.' },
  { id:14, cat:'jewelry', name:'Anaya Emerald Bridal Set', price:175, was:null, rating:5.0, reviews:3, badge:'New', stock:true, added:7,
    img:'images/emerald-bridal-set-v2.jpg',
    desc:'A statement necklace-and-earring set in emerald-green stonework with a dense floral gold setting. Finished with a pearl-beaded adjustable cord.' },
  { id:15, cat:'jewelry', name:'Alina Sapphire Bridal Set', price:195, was:null, rating:5.0, reviews:3, badge:'New', stock:true, added:8,
    img:'images/sapphire-bridal-set-v2.jpg',
    desc:'Our most elaborate set — layered sapphire-blue stones in a double-strand necklace with a detachable pendant drop, paired with matching statement earrings.' },
  { id:16, cat:'suits', name:'Mahnoor Velvet Bridal 3PC', price:145, was:null, rating:5.0, reviews:4, badge:'Best Seller', stock:true, added:9,
    images:['images/teal-suit-new1.jpg','images/teal-suit-new2.jpg'],
    desc:'Heavyweight teal velvet, densely hand-embroidered in gold thread with a matching potli bag and gold-bordered dupatta. Our most requested bridal piece this season.',
    sizes:['S','M','L','XL'] },
  { id:17, cat:'suits', name:'Sadaf Bandhani Mehndi 3PC', price:115, was:null, rating:4.9, reviews:3, badge:'New', stock:true, added:10,
    images:['images/red-suit-1.jpg','images/red-suit-2.jpg'],
    desc:'Sleeveless bandhani-print kurta with hand-embroidered neckline detailing, matching gharara pants, and a beaded potli bag — designed for mehndi and festive daytime events.',
    sizes:['XS','S','M','L','XL'] },
  { id:18, cat:'suits', name:'Rukhsar Rose Embroidered 3PC', price:135, was:null, rating:5.0, reviews:2, badge:'New', stock:true, added:11,
    images:['images/suit-blackred-1.jpg','images/suit-blackred-2.jpg','images/suit-blackred-3.jpg'],
    desc:'Black georgette kurta with hand-appliquéd rose embroidery at the neckline, sheer sleeves, and a matching embroidered potli bag with a deep red dupatta.',
    sizes:['S','M','L','XL'] },
  { id:19, cat:'suits', name:'Haniya Jewel-Tone Bridal 3PC', price:155, was:null, rating:5.0, reviews:1, badge:'New', stock:true, added:12,
    images:['images/blackpurple-new.jpg'],
    desc:'Statement bridal piece in black with dense gold embroidery, a contrasting purple-and-red dupatta with teal accents, and beaded tassel cuffs. A true showpiece.',
    sizes:['S','M','L','XL'] },
  { id:20, cat:'bags', name:'Gulbahar Sequin Clutch', price:42, was:null, rating:4.8, reviews:2, badge:'New', stock:true, added:13,
    images:['images/bag-floral-1.jpg','images/bag-floral-2.jpg'],
    desc:'A fully hand-sequinned box clutch with a floral motif and a gold kiss-lock clasp. A bold, colorful finishing piece for festive outfits.' },
  { id:21, cat:'bags', name:'Wafa Phoenix Brocade Clutch', price:38, was:null, rating:4.7, reviews:1, badge:'New', stock:true, added:14,
    img:'images/bag-teal-brocade.jpg',
    desc:'Teal silk brocade kiss-lock bag with a woven phoenix motif in gold and rose thread, finished with a gold chain strap.' },
  { id:22, cat:'bags', name:'Meira Wave Brocade Clutch', price:36, was:null, rating:4.7, reviews:1, badge:'New', stock:true, added:15,
    img:'images/bag-navy-wave.jpg',
    desc:'Navy silk brocade kiss-lock bag with a woven wave motif, gold frame clasp, and a silk tassel charm.' },
  { id:23, cat:'bags', name:'Farheen Butterfly Brocade Clutch', price:34, was:null, rating:4.6, reviews:1, badge:'New', stock:true, added:16,
    img:'images/bag-butterfly.jpg',
    desc:'Ivory silk brocade kiss-lock bag with a woven blue butterfly motif, gold frame clasp, and a red tassel charm.' },
  { id:24, cat:'suits', name:'Areeba Rose Garden 3PC', price:68, was:null, rating:4.8, reviews:1, badge:'New', stock:true, added:17,
    img:'images/pink-floral-suit.jpg',
    desc:'Dusty rose three-piece with hand-embroidered floral detailing at the neckline and cuffs, and a matching lightweight dupatta. A softer, everyday-elegant piece for daytime events.',
    sizes:['XS','S','M','L','XL'] },
  { id:25, cat:'suits', name:'Zoha Royal Velvet 3PC', price:235, was:null, rating:5.0, reviews:1, badge:'New', stock:true, added:18,
    images:['images/purple-velvet-1.jpg','images/purple-velvet-2.jpg'],
    desc:'A statement velvet piece in deep purple with dense metallic embroidery throughout, a heavily embellished matching dupatta, and delicate beaded trim. A rare, limited piece.',
    sizes:['L'] },
  { id:26, cat:'suits', name:'Hadiya Gilded Chiffon 3PC', price:235, was:null, rating:5.0, reviews:1, badge:'New', stock:true, added:19,
    img:'images/beige-chiffon-suit.jpg',
    desc:'Soft gold chiffon with dense hand-embroidered florals cascading from neckline to hem, paired with a matching scalloped-edge dupatta. An elegant evening piece.',
    sizes:['M'] },
  { id:27, cat:'suits', name:'Kiran Noir Velvet 3PC', price:175, was:null, rating:4.9, reviews:1, badge:'New', stock:true, added:20,
    images:['images/black-velvet-1.jpg','images/black-velvet-2.jpg'],
    desc:'Black velvet with fine gold floral embroidery throughout, paired with a warm tan organza dupatta bordered in deep maroon and violet panels.',
    sizes:['M'] },
];
